CREATE SCHEMA "public";
CREATE TABLE "cache" (
	"key" varchar(255) PRIMARY KEY,
	"value" text NOT NULL,
	"expiration" bigint NOT NULL
);
CREATE TABLE "cache_locks" (
	"key" varchar(255) PRIMARY KEY,
	"owner" varchar(255) NOT NULL,
	"expiration" bigint NOT NULL
);
CREATE TABLE "directorates" (
	"Directorate_id" integer PRIMARY KEY,
	"Directorate_Name" varchar(255),
	"created_at" timestamp,
	"updated_at" timestamp
);
CREATE TABLE "failed_jobs" (
	"id" bigserial PRIMARY KEY,
	"uuid" varchar(255) NOT NULL CONSTRAINT "failed_jobs_uuid_unique" UNIQUE,
	"connection" varchar(255) NOT NULL,
	"queue" varchar(255) NOT NULL,
	"payload" text NOT NULL,
	"exception" text NOT NULL,
	"failed_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE "job_batches" (
	"id" varchar(255) PRIMARY KEY,
	"name" varchar(255) NOT NULL,
	"total_jobs" integer NOT NULL,
	"pending_jobs" integer NOT NULL,
	"failed_jobs" integer NOT NULL,
	"failed_job_ids" text NOT NULL,
	"options" text,
	"cancelled_at" integer,
	"created_at" integer NOT NULL,
	"finished_at" integer
);
CREATE TABLE "jobs" (
	"id" bigserial PRIMARY KEY,
	"queue" varchar(255) NOT NULL,
	"payload" text NOT NULL,
	"attempts" smallint NOT NULL,
	"reserved_at" integer,
	"available_at" integer NOT NULL,
	"created_at" integer NOT NULL
);
CREATE TABLE "migrations" (
	"id" serial PRIMARY KEY,
	"migration" varchar(255) NOT NULL,
	"batch" integer NOT NULL
);
CREATE TABLE "password_reset_tokens" (
	"email" varchar(255) PRIMARY KEY,
	"token" varchar(255) NOT NULL,
	"created_at" timestamp
);
CREATE TABLE "schools" (
	"School_ID" integer PRIMARY KEY,
	"SchoolName" varchar(255),
	"directorate_id" integer NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
CREATE TABLE "sessions" (
	"id" varchar(255) PRIMARY KEY,
	"user_id" bigint,
	"ip_address" varchar(45),
	"user_agent" text,
	"payload" text NOT NULL,
	"last_activity" integer NOT NULL
);
CREATE TABLE "super_visors" (
	"SuperVisor_id" integer PRIMARY KEY,
	"SuperVisor_Name" varchar(255),
	"SuperVisor_Major" varchar(255),
	"password" varchar(255) NOT NULL,
	"remember_token" varchar(100),
	"created_at" timestamp,
	"updated_at" timestamp,
	"role" varchar(255) DEFAULT 'user' NOT NULL,
	"directorate_id" integer NOT NULL,
	CONSTRAINT "super_visors_role_check" CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'user'::character varying])::text[])))
);
CREATE TABLE "teacher_grades" (
	"teacher_id" integer PRIMARY KEY,
	"score1" integer NOT NULL,
	"score2" integer NOT NULL,
	"score3" integer NOT NULL,
	"score4" integer NOT NULL,
	"score5" integer NOT NULL,
	"score6" integer NOT NULL,
	"score7" integer NOT NULL,
	"score8" integer NOT NULL,
	"score9" integer NOT NULL,
	"score10" integer NOT NULL,
	"score11" integer NOT NULL,
	"score12" integer NOT NULL,
	"score13" integer NOT NULL,
	"score14" integer NOT NULL,
	"score15" integer NOT NULL,
	"score16" integer NOT NULL,
	"score17" integer NOT NULL,
	"score18" integer NOT NULL,
	"score19" integer NOT NULL,
	"score20" integer NOT NULL,
	"score21" integer NOT NULL,
	"score22" integer NOT NULL,
	"total" integer NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
CREATE TABLE "teacher_infos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teacher_infos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supervisor_id" integer NOT NULL,
	"Teacher_Name" varchar(255) NOT NULL,
	"Teacher_id" integer NOT NULL CONSTRAINT "teacher_infos_teacher_id_unique" UNIQUE,
	"school_id" integer NOT NULL,
	"date" date NOT NULL,
	"teacher_qualify" varchar(255) NOT NULL,
	"teacher_major" varchar(255) NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp,
	"supervisor_note" text
);
CREATE TABLE "teacher_justifications" (
	"teacher_id" integer PRIMARY KEY,
	"strengths" text,
	"weaknesses" text,
	"recommendations" text,
	"preparer_opinion" text,
	"approver_notes" text,
	"created_at" timestamp,
	"updated_at" timestamp
);
CREATE TABLE "users" (
	"id" bigserial PRIMARY KEY,
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL CONSTRAINT "users_email_unique" UNIQUE,
	"email_verified_at" timestamp,
	"password" varchar(255) NOT NULL,
	"remember_token" varchar(100),
	"created_at" timestamp,
	"updated_at" timestamp
);
CREATE INDEX "cache_expiration_index" ON "cache" ("expiration");
CREATE UNIQUE INDEX "cache_pkey" ON "cache" ("key");
CREATE INDEX "cache_locks_expiration_index" ON "cache_locks" ("expiration");
CREATE UNIQUE INDEX "cache_locks_pkey" ON "cache_locks" ("key");
CREATE UNIQUE INDEX "directorates_pkey" ON "directorates" ("Directorate_id");
CREATE INDEX "failed_jobs_connection_queue_failed_at_index" ON "failed_jobs" ("connection","queue","failed_at");
CREATE UNIQUE INDEX "failed_jobs_pkey" ON "failed_jobs" ("id");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" ON "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "job_batches_pkey" ON "job_batches" ("id");
CREATE UNIQUE INDEX "jobs_pkey" ON "jobs" ("id");
CREATE INDEX "jobs_queue_index" ON "jobs" ("queue");
CREATE UNIQUE INDEX "migrations_pkey" ON "migrations" ("id");
CREATE UNIQUE INDEX "password_reset_tokens_pkey" ON "password_reset_tokens" ("email");
CREATE UNIQUE INDEX "schools_pkey" ON "schools" ("School_ID");
CREATE INDEX "sessions_last_activity_index" ON "sessions" ("last_activity");
CREATE UNIQUE INDEX "sessions_pkey" ON "sessions" ("id");
CREATE INDEX "sessions_user_id_index" ON "sessions" ("user_id");
CREATE UNIQUE INDEX "super_visors_pkey" ON "super_visors" ("SuperVisor_id");
CREATE UNIQUE INDEX "teacher_grades_pkey" ON "teacher_grades" ("teacher_id");
CREATE UNIQUE INDEX "teacher_infos_pkey" ON "teacher_infos" ("id");
CREATE UNIQUE INDEX "teacher_infos_teacher_id_unique" ON "teacher_infos" ("Teacher_id");
CREATE UNIQUE INDEX "teacher_justifications_pkey" ON "teacher_justifications" ("teacher_id");
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE UNIQUE INDEX "users_pkey" ON "users" ("id");
ALTER TABLE "schools" ADD CONSTRAINT "schools_directorate_id_foreign" FOREIGN KEY ("directorate_id") REFERENCES "directorates"("Directorate_id");
ALTER TABLE "super_visors" ADD CONSTRAINT "super_visors_directorate_id_foreign" FOREIGN KEY ("directorate_id") REFERENCES "directorates"("Directorate_id");
ALTER TABLE "teacher_grades" ADD CONSTRAINT "teacher_grades_teacher_id_foreign" FOREIGN KEY ("teacher_id") REFERENCES "teacher_infos"("Teacher_id");
ALTER TABLE "teacher_infos" ADD CONSTRAINT "teacher_infos_school_id_foreign" FOREIGN KEY ("school_id") REFERENCES "schools"("School_ID");
ALTER TABLE "teacher_infos" ADD CONSTRAINT "teacher_infos_supervisor_id_foreign" FOREIGN KEY ("supervisor_id") REFERENCES "super_visors"("SuperVisor_id") ON UPDATE CASCADE;
ALTER TABLE "teacher_justifications" ADD CONSTRAINT "teacher_justifications_teacher_id_foreign" FOREIGN KEY ("teacher_id") REFERENCES "teacher_infos"("Teacher_id");