<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            return;
        }

        // Restore auto-increment behavior on teacher_infos.id
        DB::statement('SELECT setval(pg_get_serial_sequence(\'teacher_infos\', \'id\'), COALESCE((SELECT MAX(id) FROM teacher_infos), 1))');

        DB::statement('
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_attrdef ad
                    JOIN pg_attribute a ON a.attnum = ad.adnum AND a.attrelid = ad.adrelid
                    WHERE ad.adrelid = \'teacher_infos\'::regclass AND a.attname = \'id\'
                ) THEN
                    EXECUTE \'ALTER TABLE teacher_infos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY\';
                END IF;
            END $$;
        ');
    }

    public function down(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            return;
        }

        DB::statement('ALTER TABLE teacher_infos ALTER COLUMN id DROP IDENTITY IF EXISTS');
    }
};